# AP: AP-E2E-TEST-v1.0.0
# ⬡ OMEGA ⬡ VERITY ⬡ deepseek-v4-flash ⬡ opencode ⬡ E2E-VERIFICATION
#
# End-to-End Inference Chain Test
# Verifies the full loop: Query -> Router -> Gateway -> Response -> Memory -> Distiller

import os
import pytest
import anyio
from unittest.mock import MagicMock, patch

# Force test environment
os.environ["OMEGA_ENV"] = "test"

from omega.oracle.oracle import Oracle
from omega.oracle.model_gateway import ModelGateway
from omega.memory_store import MemoryStore
from omega.oracle.soul_distiller import SoulDistillationPipeline

@pytest.mark.anyio
async def test_e2e_inference_chain():
    """
    Verifies the complete cognitive run-loop of the Omega Engine.
    
    Chain:
    1. User Query -> Oracle.talk()
    2. Oracle -> SemanticRouter (Entity Selection)
    3. Oracle -> ModelGateway (Inference via MockBackend)
    4. ModelGateway -> OracleResponse (Result)
    5. Oracle -> MemoryStore (Persistence)
    6. Oracle -> SoulDistiller (Distillation on session close)
    """
    
    # 1. Setup
    oracle = Oracle()
    from omega.memory_store import get_memory_store
    memory = get_memory_store()
    
    # We mock get_distiller to verify it's called without
    # actually running the heavy distillation logic in a unit test.
    with patch("omega.oracle.oracle.get_distiller") as mock_get_distiller:
        mock_distiller = MagicMock()
        # Use AsyncMock for distill_and_save since it is awaited
        mock_distiller.distill_and_save = MagicMock()
        # To make it awaitable, we can use a lambda or a future, 
        # but the easiest way is to use AsyncMock if available or just return a future.
        from unittest.mock import AsyncMock
        mock_distiller.distill_and_save = AsyncMock(return_value=True)
        
        mock_get_distiller.return_value = mock_distiller
        
        # Re-initialize oracle to pick up the mocked distiller
        oracle = Oracle()
        await oracle.bootstrap()


        # 2. Execution
        # We use a query that should clearly map to a specific domain (e.g., 'datastore' or 'sysadmin')
        query = "I need to store some data in the vector store"
        response = await oracle.talk(query)
        
        # 3. Verifications
        
        # A. Response Integrity
        assert response is not None
        assert hasattr(response, "text")
        assert len(response.text) > 0
        
        # B. Routing Verification
        # The response should have been generated by an entity related to data/persistence
        # In the mock backend, we can check the backend name or the entity used.
        assert response.backend is not None

        
        # C. Memory Persistence
        # Check if the exchange was added to the memory store
        # We search for the query in the memory store for the responding entity
        exchanges = await memory.search_fts(query, entity_name=response.entity)
        assert len(exchanges) > 0
        assert any(query in e.get("content", "") for e in exchanges)
        
        # D. Distillation Trigger
        # The Oracle should call close_session which triggers the SoulDistiller
        # Since we are in a test, we can manually trigger close_session if the
        # automatic trigger (every 5 turns) hasn't hit yet.
        entity_name = response.entity if hasattr(response, "entity") else "default"
        session_id = response.session_id if hasattr(response, "session_id") else "test_session"


        
        await oracle.close_session(entity_name, session_id)
        
        # Verify that the distiller's distill_and_save method was called
        assert mock_distiller.distill_and_save.called
        
    print("\n✅ E2E Inference Chain Verified: Query -> Router -> Gateway -> Response -> Memory -> Distiller")

if __name__ == "__main__":
    # Allow running the test directly via python
    anyio.run(test_e2e_inference_chain)
