#!/usr/bin/env python3
"""Render EXPERT_SESSION_REGISTRY.md from the Tier-3 SSOT (M4 / G4-Ruling-4).

Sources of truth:
  - data/coordination/TASK_REGISTRY.json      (task records)
  - data/coordination/session_annotations.yaml (judgments attach to records)

Emits: GENERATED header stamp, summary table (id/agent/entity/domain/
status/artifact_path), domain index + agent-type index (domain falls back to
first tag when absent), computed hygiene section, inline annotations, and a
link to the narrative companion (EXPERT_SESSION_REGISTRY_NARRATIVE.md) which
preserves analyst prose that is NOT derivable from JSON (G5-3).

Atomic write (tmp->rename). Run manually or via `make session-registry`.
Stdlib + PyYAML only (PyYAML already a project dependency).
"""
import json
import os
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

import yaml

SCRIPTS_DIR = Path(__file__).parent
sys.path.insert(0, str(SCRIPTS_DIR))
from validate_tracking_state import (  # noqa: E402
    DATA_DIR,
    ROOT_DIR,
    STALENESS_DAYS,
    TASK_REGISTRY_PATH,
    _parse_ts,
)

ANNOTATIONS_PATH = DATA_DIR / "session_annotations.yaml"
OUTPUT_PATH = DATA_DIR / "EXPERT_SESSION_REGISTRY.md"
NARRATIVE_PATH = DATA_DIR / "EXPERT_SESSION_REGISTRY_NARRATIVE.md"

HEADER_STAMP = (
    "<!-- GENERATED by generate_session_registry.py — DO NOT EDIT; "
    "edit TASK_REGISTRY.json / session_annotations.yaml -->"
)


def task_domain(t):
    """Explicit `domain` field, else first tag, else '(untagged)'."""
    if t.get("domain"):
        return str(t["domain"])
    tags = t.get("tags") or []
    return str(tags[0]) if tags else "(untagged)"


def esc(s):
    return str(s).replace("|", "\\|").strip() if s else "—"


def render(registry, annotations):
    tasks = registry.get("tasks", [])
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        HEADER_STAMP,
        "",
        "# 🔱 Expert Session Registry (GENERATED VIEW)",
        "",
        f"**Generated**: {now} · **Sources**: `TASK_REGISTRY.json` ({len(tasks)} tasks), "
        f"`session_annotations.yaml` ({len(annotations)} annotations)",
        "",
        "> **Narrative companion**: analyst prose, quality assessments, and chain-of-custody",
        f"> notes live in [`EXPERT_SESSION_REGISTRY_NARRATIVE.md`]({NARRATIVE_PATH.name}) — "
        "they are NOT derivable from JSON (G5-3). Consult it alongside this view.",
        "",
        "## §1 Summary Table",
        "",
        "| Task ID | Agent | Entity | Domain | Status | Artifact Path |",
        "|---|---|---|---|---|---|",
    ]
    for t in tasks:
        lines.append(
            f"| `{esc(t.get('task_id'))}` | {esc(t.get('subagent_type'))} "
            f"| {esc(t.get('entity') or t.get('executed_by'))} "
            f"| {esc(task_domain(t))} | {esc(t.get('status'))} "
            f"| {esc(t.get('artifact_path'))} |"
        )

    # Domain index (GROUP BY domain, fallback first-tag per G4-R2)
    by_domain = {}
    for t in tasks:
        by_domain.setdefault(task_domain(t), []).append(t.get("task_id"))
    lines += ["", "## §2 Domain Index", ""]
    for dom in sorted(by_domain):
        lines.append(f"- **{dom}** ({len(by_domain[dom])}): " + ", ".join(f"`{i}`" for i in by_domain[dom]))

    # Agent-type index
    by_agent = {}
    for t in tasks:
        agent = t.get("subagent_type") or "(none)"
        by_agent.setdefault(agent, []).append(t.get("task_id"))
    lines += ["", "## §3 Agent-Type Index", ""]
    for agent in sorted(by_agent):
        lines.append(f"- **{agent}** ({len(by_agent[agent])}): " + ", ".join(f"`{i}`" for i in by_agent[agent]))

    # Computed hygiene section (replaces hand-written findings, G4-R3)
    now_dt = datetime.now(timezone.utc)
    stale = [t for t in tasks
             if t.get("status") == "in_progress"
             and (ts := _parse_ts(t.get("last_checkpoint")))
             and (now_dt - ts).days > STALENESS_DAYS]
    sup_no_ptr = [t for t in tasks
                  if t.get("status") == "superseded" and not (t.get("superseded_by") or "").strip()]
    untagged = [t for t in tasks if not t.get("tags")]
    lines += [
        "", "## §4 Computed Hygiene", "",
        f"- Stale `in_progress` (> {STALENESS_DAYS}d): **{len(stale)}**"
        + (": " + ", ".join(f"`{t['task_id']}`" for t in stale) if stale else ""),
        f"- `superseded` without pointer: **{len(sup_no_ptr)}**"
        + (": " + ", ".join(f"`{t['task_id']}`" for t in sup_no_ptr) if sup_no_ptr else ""),
        f"- Untagged tasks (`tags: []`): **{len(untagged)}**"
        + (": " + ", ".join(f"`{t['task_id']}`" for t in untagged) if untagged else ""),
    ]

    # Annotations rendered inline (Langfuse score-object pattern)
    ann_by_target = {}
    for a in annotations:
        ann_by_target.setdefault(a.get("target", ""), []).append(a)
    lines += ["", "## §5 Annotations (session_annotations.yaml)", ""]
    if not annotations:
        lines.append("_(none)_")
    for target, anns in ann_by_target.items():
        lines.append(f"### `{target}`")
        for a in anns:
            evidence = "; ".join(str(e) for e in (a.get("evidence") or [])) or "—"
            comment = " ".join(str(a.get("comment", "")).split())
            lines += [
                f"- **{a.get('verdict', '—')}** by *{a.get('assessor', '—')}* "
                f"at {a.get('assessed_at', '—')} (`{a.get('annotation_id', '—')}`)",
                f"  - Evidence: {evidence}",
                f"  - Comment: {comment}" if comment else "",
            ]
        lines.append("")
    return "\n".join(l for l in lines if l is not None) + "\n"


def atomic_write(path, content):
    fd, tmp = tempfile.mkstemp(dir=str(path.parent), suffix=".tmp")
    try:
        with os.fdopen(fd, "w") as f:
            f.write(content)
        # mkstemp creates 0600; match repo-standard 0644 so other agents can read.
        os.chmod(tmp, 0o644)
        os.replace(tmp, path)
    except BaseException:
        if os.path.exists(tmp):
            os.unlink(tmp)
        raise


def main():
    registry = json.loads(TASK_REGISTRY_PATH.read_text())
    annotations = []
    if ANNOTATIONS_PATH.exists():
        data = yaml.safe_load(ANNOTATIONS_PATH.read_text()) or {}
        annotations = data.get("annotations", []) or []
    else:
        print(f"WARNING: {ANNOTATIONS_PATH.name} not found; rendering without annotations.",
              file=sys.stderr)
    content = render(registry, annotations)
    atomic_write(OUTPUT_PATH, content)
    n_tasks = len(registry.get("tasks", []))
    print(f"Wrote {OUTPUT_PATH} ({n_tasks} tasks, {len(annotations)} annotations).")


if __name__ == "__main__":
    main()
