#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Xoe-NovAi
#
# SPDX-License-Identifier: Apache-2.0
#
# test_lan_exposure_audit.py — negative tests for `make check-lan-exposure`.
#
# THIS IS A STANDALONE SCRIPT, NOT A PYTEST MODULE. It defines no module-level
# `test_*` functions, so `pytest` correctly collects 0 tests from it. Run it
# directly — `python scripts/test_lan_exposure_audit.py` (Makefile:417, :1149).
# A gate that has never been observed failing is not a gate.
#
# ##########################################################################
# # WHY THIS FILE WAS REWRITTEN (D-616)                                       #
# #                                                                          #
# # D-612 sanitized the real host addresses out of BOTH the allowlist AND    #
# # this test in the same commit. That is the textbook way to build a test   #
# # that agrees with itself: both sides of every assertion moved together,    #
# # so the suite reported 29/29 green while asserting nothing about the      #
# # machine it runs on. Meanwhile the real gate — the one that reads the      #
# # allowlist and compares it to live `ss` output — went RED on three real    #
# # tailscaled binds, because `<TAILSCALE_IFACE>` cannot match `tailscale0`.  #
# #                                                                          #
# # A test whose fixtures are edited in the same commit as the thing under    #
# # test cannot fail when the thing under test breaks. That is the defect.    #
# #                                                                          #
# # THE FIX: this suite no longer reads the tracked template for its         #
# # "approved" cases. It builds a SYNTHETIC host-local override in a temp    #
# # file — realistic shape, fake values (RFC 6598 CGNAT 100.64.0.1, an       #
# # obviously-synthetic fd7a: ULA, iface `tailscale0`) — and loads the audit  #
# # policy through the real `load_allowlist()` merge path. The tracked        #
# # template is then free to be placeholder-only forever, because the test's  #
# # approved-address expectations no longer come from it.                     #
# #                                                                          #
# # Section B goes further and asserts the DISCRIMINATION directly: it loads  #
# # the same synthetic override with local precedence enabled and disabled,   #
# # and requires the verdict to FLIP. If someone deletes the overlay merge    #
# # from `load_allowlist`, section B goes red. It cannot be satisfied by a    #
# # fixture that moved with the implementation.                               #
# ##########################################################################
#
# Every case below is synthetic: it feeds `classify()` a constructed Listener
# and asserts the verdict. No socket is opened, no service is touched, nothing
# on the host is mutated. The only filesystem write is a TemporaryDirectory.

from __future__ import annotations

import os
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import lan_exposure_audit as lea  # noqa: E402

PASS = "\033[0;32m"
FAIL = "\033[0;31m"
NC = "\033[0m"

# ---------------------------------------------------------------------------
# SYNTHETIC host-local reality. Fake values, realistic shape.
#
# These are NOT this host's addresses and must never be written down here.
# n0's real tailnet v4 and v6 are host-identifying; both leaked into the tracked
# template AND into the pre-D-616 version of this file, which is how D-612's
# partial sanitization survived review. Do not paste a real value here "just to
# document the regression" — that is the exact defect being fixed.
# 100.64.0.1 is the first address in the RFC 6598 CGNAT block Tailscale draws
# from, so it exercises the exact same classification path as the real thing
# while naming no machine.
# ---------------------------------------------------------------------------
SYN_V4 = "100.64.0.1"
SYN_V6 = "fd7a:dead:beef::1"
SYN_IFACE = "tailscale0"
SYN_PEERAPI_PORT = 43961

SYNTHETIC_LOCAL = f"""
# synthetic host-local override — generated by test_lan_exposure_audit.py
version: 99
updated: "synthetic"
tailnet_addresses:
  - {SYN_V4}
  - {SYN_V6}
tailnet_interfaces:
  - {SYN_IFACE}
allowed_tailnet_bindings:
  - address: "{SYN_V4}"
    port: 8016
    process: "tailscaled"
    reason: "synthetic: Hub MCP Serve route"
  - address: "{SYN_V4}"
    port: 8019
    process: "tailscaled"
    reason: "synthetic: exchange pipe Serve route"
  - address: "{SYN_V4}"
    port: {SYN_PEERAPI_PORT}
    process: "tailscaled"
    reason: "synthetic: peerapi IPv4"
  - address: "{SYN_V6}"
    port: 8016
    process: "tailscaled"
    reason: "synthetic: Hub MCP IPv6 twin"
  - address: "{SYN_V6}"
    port: 8019
    process: "tailscaled"
    reason: "synthetic: exchange pipe IPv6 twin"
  - address: "{SYN_V6}"
    port: 40656
    process: "tailscaled"
    reason: "synthetic: peerapi IPv6"
"""


def L(addr: str, port: int, ifname: str | None = None, proc: str | None = None):
    return lea.Listener(addr, port, ifname, proc)


def _build_synthetic_policies() -> tuple[dict, dict]:
    """Load (effective, tracked-only) policy through the REAL merge path.

    The temp dir is removed as soon as both dicts are in memory — the policies
    are plain dicts and no longer need the file. This runs at import time so
    that `tests/test_lan_exposure.py` can import ALLOW/CASES and parametrise
    over them; that wrapper's contract is "no case duplicated, no logic
    reimplemented", so the table has to live at module scope.
    """
    with tempfile.TemporaryDirectory(prefix="lan-audit-fixture-") as td:
        p = Path(td) / "lan_exposure_allowlist.local.yaml"
        p.write_text(SYNTHETIC_LOCAL)
        return (
            lea.load_allowlist(local_path=p),
            lea.load_allowlist(local_path=p, use_local=False),
        )


# Effective policy (synthetic override merged over the tracked template) and the
# tracked template alone. Module-level so the pytest wrapper can import them.
ALLOW, TRACKED_ONLY = _build_synthetic_policies()

# (name, listener, should_be_clean)
#
# Every "approved" case below is approved ONLY because ALLOW carries the
# synthetic override. Not one of these addresses appears in the tracked
# template — that is what makes this table independent of the file D-612
# sanitized, and therefore able to disagree with it.
CASES = [
    # --- must be CLEAN: loopback and link-local are never exposures ---
    ("loopback v4 ignored", L("127.0.0.1", 8016, None, "python"), True),
    ("loopback v4 alt ignored", L("127.0.0.54", 53, None, None), True),
    ("loopback v6 ::1 ignored", L("::1", 631, None, None), True),
    (
        "link-local fe80 ignored (the bug this caught)",
        L("fe80::70ed:3d61:6fe7:a202", 44348, "wlan0", "rygel"),
        True,
    ),
    (
        "link-local fe80 veth ignored",
        L("fe80::2c96:56ff:fe1e:8555", 58532, "veth_host_3", "rygel"),
        True,
    ),
    # --- must be CLEAN: approved tailnet binds, via the LOCAL OVERLAY ---
    ("approved tailnet 8016 v4 (via local override)", L(SYN_V4, 8016, None, None), True),
    ("approved tailnet 8019 v4 (via local override)", L(SYN_V4, 8019, None, None), True),
    ("approved tailnet peerapi v4 (via local override)", L(SYN_V4, SYN_PEERAPI_PORT, None, None), True),
    ("approved tailnet 8016 v6 (via local override)", L(SYN_V6, 8016, None, None), True),
    ("approved tailnet 8019 v6 (via local override)", L(SYN_V6, 8019, None, None), True),
    ("approved tailnet peerapi v6 (via local override)", L(SYN_V6, 40656, None, None), True),
    # --- must be FLAGGED: the exact regressions this gate was built to catch ---
    ("WILDCARD nfsd 2049 caught", L("0.0.0.0", 2049, None, None), False),
    ("WILDCARD mountd 20048 caught", L("0.0.0.0", 20048, None, None), False),
    ("WILDCARD lockd 32803 caught", L("0.0.0.0", 32803, None, None), False),
    ("WILDCARD redis 6379 caught", L("0.0.0.0", 6379, None, "pasta.avx2"), False),
    ("WILDCARD rpcbind 111 caught", L("0.0.0.0", 111, None, None), False),
    ("WILDCARD v6 rpcbind :: caught", L("::", 111, None, None), False),
    ("LAN deluged on wifi caught", L("192.168.1.100", 51372, "wlan0", "deluged"), False),
    ("TAILNET deluged caught (iface only, port unapproved)", L(SYN_V4, 51372, SYN_IFACE, "deluged"), False),
    ("LAN docker veth caught", L("10.0.3.1", 51372, "veth_host_3", "deluged"), False),
    ("LAN rygel caught", L("10.0.1.1", 50158, "veth_host_1", "rygel"), False),
    ("bridge 172.17.0.1 caught", L("172.17.0.1", 45907, None, "rygel"), False),
    # --- boundary: approved PORT but different PORT must still be caught ---
    ("8016 approved but 9999 is not", L(SYN_V4, 9999, None, None), False),
    # --- boundary: approved address+port owned by a DIFFERENT process ---
    (
        "approved addr+port, foreign process still caught",
        L(SYN_V4, 8016, None, "evil-daemon"),
        False,
    ),
    # --- boundary: a NEIGHBOURING tailnet address is not covered ---
    ("adjacent tailnet addr not covered by entry", L("100.64.0.2", 8016, None, None), False),
    # --- unknown addr on the tailnet iface: still unapproved ---
    ("unknown addr on tailnet iface is still unapproved", L("100.64.9.9", 8016, SYN_IFACE, "tailscaled"), False),
    # --- a placeholder entry must approve nothing ---
    ("placeholder address approves nothing", L("<N0_TAILNET_IPV4>", 8016, None, None), False),
]

# (name, listener, expected_kind) — asserts the CLASS, not just clean/flagged.
KIND_CASES = [
    (
        "unknown addr on tailnet iface files as TAILNET not LAN",
        L("100.64.9.9", 8016, SYN_IFACE, "tailscaled"),
        "TAILNET",
    ),
    ("non-tailnet iface files as LAN", L("192.168.1.100", 8016, "wlan0", "tailscaled"), "LAN"),
    ("wildcard bind files as LAN", L("0.0.0.0", 2049, None, None), "LAN"),
]

# CI-exemption cases are kept out of CASES because they depend on the
# GITHUB_ACTIONS env var being toggled at run time; the pytest wrapper does not
# exercise them (unchanged from the pre-D-616 suite).

results: list[tuple[str, bool, str]] = []


def check(name: str, ok: bool, detail: str = "") -> None:
    results.append((name, ok, detail))


def classify_case(
    name: str, listener: lea.Listener, expect_clean: bool, allow: dict
) -> None:
    """Assert classify() agrees (or disagrees) with the expected verdict."""
    verdict = lea.classify(listener, allow)
    is_clean = verdict is None
    ok = is_clean == expect_clean
    expect = "clean" if expect_clean else "FLAGGED"
    got = "clean" if is_clean else f"flagged({verdict[0]})"
    detail = f"expected={expect:<8} got={got}"
    if ok:
        check(name, True, detail)
    else:
        check(name, False, detail)


def classify_kind_case(
    name: str, listener: lea.Listener, expect_kind: str, allow: dict
) -> None:
    """Assert a listener is reported with a specific KIND (TAILNET vs LAN).

    Needed because "is it clean" and "which class is it" are different
    questions. `tailnet_interfaces` decides the CLASS; the address+port
    allowlist decides whether it is APPROVED. An unknown address sitting on the
    tailnet interface is correctly still FLAGGED — it is just correctly filed as
    TAILNET rather than LAN, and only the kind assertion can see that.
    """
    verdict = lea.classify(listener, allow)
    got = "clean" if verdict is None else verdict[0]
    ok = got == expect_kind
    check(name, ok, f"expected={expect_kind:<8} got={got}")


def main() -> int:
    print("LAN EXPOSURE AUDIT — negative tests")
    print("=" * 74)
    print(f"synthetic tailnet v4 : {SYN_V4}      iface: {SYN_IFACE}")
    print(f"synthetic tailnet v6 : {SYN_V6}")
    print()

    with tempfile.TemporaryDirectory(prefix="lan-audit-test-") as td:
        syn_path = Path(td) / "lan_exposure_allowlist.local.yaml"
        syn_path.write_text(SYNTHETIC_LOCAL)

        print("--- A. classify() against the synthetic host-local override ---")
        for name, listener, expect_clean in CASES:
            classify_case(name, listener, expect_clean, ALLOW)
        for name, listener, expect_kind in KIND_CASES:
            classify_kind_case(name, listener, expect_kind, ALLOW)

        print()
        print("--- B. LOCAL-OVERRIDE PRECEDENCE IS LOAD-BEARING (D-616) ---")
        print("    These assert the merge changes the verdict. Delete the overlay")
        print("    from load_allowlist() and this section goes red.")
        probe = L(SYN_V4, 8016, None, None)
        with_local = lea.classify(probe, ALLOW)
        without_local = lea.classify(probe, TRACKED_ONLY)
        check(
            "override ON  -> approved tailnet bind is clean",
            with_local is None,
            f"got={'clean' if with_local is None else f'flagged({with_local[0]})'}",
        )
        check(
            "override OFF -> same bind is FLAGGED (gate not silently blind)",
            without_local is not None,
            f"got={'clean' if without_local is None else f'flagged({without_local[0]})'}",
        )
        check(
            "verdict genuinely FLIPS with precedence toggled",
            (with_local is None) != (without_local is None),
            "the two policies disagree, which is what makes this discriminating",
        )
        # The tracked template must NOT contain the synthetic address, or the
        # test would be agreeing with the template again.
        check(
            "synthetic addr absent from tracked template",
            SYN_V4 not in str(TRACKED_ONLY),
            "if this fails the template grew a real-looking value",
        )
        # And the merge must be REPLACEMENT, not concatenation: the template's
        # placeholder must not survive into the effective policy.
        check(
            "merge REPLACES tailnet_interfaces (no dead placeholder)",
            lea._as_list(ALLOW.get("tailnet_interfaces")) == [SYN_IFACE],
            f"got={lea._as_list(ALLOW.get('tailnet_interfaces'))}",
        )
        check(
            "merge REPLACES tailnet_addresses (no dead placeholder)",
            lea._as_list(ALLOW.get("tailnet_addresses")) == [SYN_V4, SYN_V6],
            f"got={lea._as_list(ALLOW.get('tailnet_addresses'))}",
        )
        # A key absent from the overlay is inherited from the template.
        check(
            "un-overridden key inherited from template",
            lea._as_list(ALLOW.get("allowed_lan_bindings")) == [],
            "allowed_lan_bindings must stay empty — no LAN bind is approved",
        )
        check(
            "un-overridden key inherits template LAN policy",
            "0.0.0.0" not in str(ALLOW.get("always_exempt_addresses")),
            "wildcard must never become exempt",
        )

        print()
        print("--- C. PLACEHOLDER INTEGRITY (the D-612 signature) ---")
        ph_tracked = lea.find_placeholders(TRACKED_ONLY)
        ph_effective = lea.find_placeholders(ALLOW)
        check(
            "tracked template IS placeholder-only (nothing real ships)",
            len(ph_tracked) > 0,
            f"{len(ph_tracked)} placeholders present in template",
        )
        check(
            "override clears every placeholder from effective policy",
            ph_effective == [],
            f"leaked={[f'{k}={v}' for k, v in ph_effective]}",
        )
        check(
            "find_placeholders detects the D-612 exact value",
            any(v == "<TAILSCALE_IFACE>" for _, v in ph_tracked),
            "guards against the specific regression that started this",
        )
        # A placeholder entry must not approve a real bind.
        classify_case(
            "placeholder address approves nothing",
            L("<N0_TAILNET_IPV4>", 8016, None, None),
            False,
            ALLOW,
        )

        print()
        print("--- D. OVERRIDE DISCOVERY + ENV PRECEDENCE ---")
        _, local_seen = lea.effective_sources(local_path=syn_path)
        check(
            "explicit override path is discovered",
            local_seen == syn_path,
            f"got={local_seen}",
        )
        saved_env = os.environ.pop(lea.LOCAL_OVERRIDE_ENV, None)
        os.environ[lea.LOCAL_OVERRIDE_ENV] = str(syn_path)
        env_allow = lea.load_allowlist()
        check(
            f"${lea.LOCAL_OVERRIDE_ENV} is honoured",
            lea._as_list(env_allow.get("tailnet_interfaces")) == [SYN_IFACE],
            f"got={lea._as_list(env_allow.get('tailnet_interfaces'))}",
        )
        os.environ[lea.LOCAL_OVERRIDE_ENV] = str(Path(td) / "does-not-exist.yaml")
        missing_allow = lea.load_allowlist()
        check(
            "env override pointing nowhere degrades to tracked template",
            lea._as_list(missing_allow.get("tailnet_interfaces"))
            != lea._as_list(env_allow.get("tailnet_interfaces")),
            "no phantom policy from a missing file",
        )
        try:
            lea.load_allowlist(local_path=Path(td) / "does-not-exist.yaml")
            check("explicit missing override raises SystemExit", False, "returned silently")
        except SystemExit:
            check("explicit missing override raises SystemExit", True)
        if saved_env is None:
            os.environ.pop(lea.LOCAL_OVERRIDE_ENV, None)
        else:
            os.environ[lea.LOCAL_OVERRIDE_ENV] = saved_env

        print()
        print("--- E. runner-scoped sshd exemption (PR #5 post-merge CI, 2026-10-03) ---")
        # The exemption must hold ONLY under GITHUB_ACTIONS. Pin both directions:
        # without the env a wildcard :22 must still be caught (Node 0 full
        # strength), and under the env nothing but port 22 may be excused.
        saved_ga = os.environ.pop("GITHUB_ACTIONS", None)
        classify_case("no-CI: wildcard sshd :22 caught", L("0.0.0.0", 22, None, None), False, ALLOW)
        classify_case("no-CI: wildcard v6 sshd :::22 caught", L("::", 22, None, None), False, ALLOW)
        os.environ["GITHUB_ACTIONS"] = "true"
        classify_case("CI runner: wildcard sshd :22 exempt", L("0.0.0.0", 22, None, None), True, ALLOW)
        classify_case("CI runner: wildcard v6 sshd :::22 exempt", L("::", 22, None, None), True, ALLOW)
        classify_case("CI runner: wildcard :2222 still caught", L("0.0.0.0", 2222, None, None), False, ALLOW)
        classify_case("CI runner: wildcard nfsd 2049 still caught", L("0.0.0.0", 2049, None, None), False, ALLOW)
        classify_case(
            "CI runner: LAN sshd on real IP still caught",
            L("10.0.3.1", 22, None, "sshd"),
            False,
            ALLOW,
        )
        if saved_ga is None:
            os.environ.pop("GITHUB_ACTIONS", None)
        else:
            os.environ["GITHUB_ACTIONS"] = saved_ga

    print("=" * 74)
    for name, ok, detail in results:
        status = f"{PASS}PASS{NC}" if ok else f"{FAIL}FAIL{NC}"
        print(f"  [{status}] {name:<52} {detail}")

    total = len(results)
    failures = [n for n, ok, _ in results if not ok]
    print("=" * 74)
    if failures:
        print(f"{FAIL}RESULT: FAIL{NC} — {len(failures)}/{total} negative tests failed:")
        for f in failures:
            print(f"  - {f}")
        return 1
    print(f"{PASS}RESULT: PASS{NC} — {total}/{total} negative tests green.")
    print()
    print("Section B is the anti-D-612 assertion: the approved-address cases are")
    print("fed by a TEMP synthetic override, not by the tracked template, and the")
    print("verdict is required to FLIP when local precedence is disabled. A test")
    print("whose fixtures move with the implementation cannot catch a gate that")
    print("went blind — this one can.")
    return 0


if __name__ == "__main__":
    sys.exit(main())